---
apiVersion: batch/v1
kind: Job
metadata:
  name: load-container-image-${USER}
  namespace: quay-perf
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
      - command:
        - /scripts/targeted-build-script.sh
        args:
        - "${USER}"
        env:
        - name: QUAY_URL
          value: ${QUAY_URL}
        - name: TOKEN
          value: "${TOKEN}"
        - name: NUM_USERS
          value: "${NUM_USERS}"
        - name: PREFIX
          value: "${PREFIX}"
        - name: CONCURRENT_JOBS
          value: "${CONCURRENT_JOBS}"
        image: quay.io/openshift-scale/scale-ci-workload:master
        imagePullPolicy: Always
        name: load
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /scripts
          name: load-script
      volumes:
      - configMap:
          defaultMode: 484
          name: load-script
        name: load-script
      restartPolicy: Never

